language: node_js

node_js:
  - "node"

install:
  # - npm install -g codecov

dist: trusty

services:
  - postgres

addons:
  postgresql: "9.5"

before_script:
  - psql --version
  - service postgresql status
  - psql -U postgres -c 'create database test_db;'

env:
  global:
  - PGPORT=5432qa
  - PGHOST=localhost
  - NODE_ENV=test
  # - CODECOV_TOKEN="fe328c6a-8a8d-4f41-9936-793d08b8666c"
 
script:
  - npm test
  # - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec && codecov
